version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:10.7
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - phevoy_db_net

networks:
  phevoy_db_net:
    external: true
